// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentSystem.Server.Data;

#nullable disable

namespace StudentSystem.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221201003116_CreateInitial")]
    partial class CreateInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentSystem.Shared.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("ClassID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Depratment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepratmentId")
                        .HasColumnType("int");

                    b.Property<string>("LecturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Timeslot")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 155,
                            ClassID = "1B",
                            CourseName = "Python Programming",
                            CreditHours = 3,
                            Day = 1,
                            Depratment = "Computer Engineering",
                            DepratmentId = 1,
                            LecturerName = "Dr.Mohammed",
                            Timeslot = 1
                        },
                        new
                        {
                            CourseId = 145,
                            ClassID = "3C",
                            CourseName = "Java Programming",
                            CreditHours = 3,
                            Day = 1,
                            Depratment = "Computer Engineering",
                            DepratmentId = 1,
                            LecturerName = "Dr.Mostafa",
                            Timeslot = 2
                        },
                        new
                        {
                            CourseId = 135,
                            ClassID = "3C",
                            CourseName = "C++ Programming",
                            CreditHours = 3,
                            Day = 1,
                            Depratment = "Computer Engineering",
                            DepratmentId = 1,
                            LecturerName = "Dr.Aly",
                            Timeslot = 3
                        },
                        new
                        {
                            CourseId = 295,
                            ClassID = "1MA",
                            CourseName = "Maths",
                            CreditHours = 3,
                            Day = 2,
                            Depratment = "Mechanical Engineering",
                            DepratmentId = 2,
                            LecturerName = "Dr.Ola",
                            Timeslot = 1
                        },
                        new
                        {
                            CourseId = 104,
                            ClassID = "3C",
                            CourseName = "Economy",
                            CreditHours = 3,
                            Day = 2,
                            Depratment = "Computer Engineering",
                            DepratmentId = 1,
                            LecturerName = "Dr.Saad",
                            Timeslot = 2
                        },
                        new
                        {
                            CourseId = 284,
                            ClassID = "3MA",
                            CourseName = "Dynamics",
                            CreditHours = 3,
                            Day = 2,
                            Depratment = "Mechanical Engineering",
                            DepratmentId = 2,
                            LecturerName = "Dr.Abdullah",
                            Timeslot = 3
                        },
                        new
                        {
                            CourseId = 109,
                            ClassID = "3C",
                            CourseName = "Statistics",
                            CreditHours = 3,
                            Day = 3,
                            Depratment = "Mechanical Engineering",
                            DepratmentId = 2,
                            LecturerName = "Dr.Omar",
                            Timeslot = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
